### ISSUE TITLE
Can you share the pre-trained model?

### ISSUE THREAD

**Issue by viethungluu** [sadrultoaha/Signboard-Detection#1]
Hi, thank you for your work. Im trying to run the notebook, but the pre-trained model from gdrive is not available for now. Can you share it again?

**Comment by sadrultoaha** [comment]
Thanks for your interest!  I'll let you know after updating the modal.

**Comment by sadrultoaha** [comment]
The model weight file has been shared, you can find the link in the readme. Due to deprecation, the Google Colab notebook has been removed as Colab no longer supports TensorFlow v1.
