### ISSUE TITLE
detection.py contains syntax errors

### ISSUE THREAD

**Issue by tekmen0** [sadrultoaha/Signboard-Detection#2]
detection.py contains syntax errors & jupyter notebook is not a valid notebook. Also fi you can share pretrained wieghts or dataset, this would be great.

Thanks.

**Comment by sadrultoaha** [comment]
The model weight file has been shared, you can find the link in the readme. Due to deprecation, the Google Colab notebook has been removed as Colab no longer supports TensorFlow v1. You can run now using detection.py, please see the details in the readme.
